# Automatically generated file. DO NOT MODIFY
#
# This file is generated by device/xiaomi/munch/setup-makefiles.sh

LOCAL_CHECK_ELF_FILES := false
LOCAL_PATH := $(call my-dir)

ifeq ($(TARGET_DEVICE),munch)

endif
